# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emcee < Formula
  desc ""
  homepage ""
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mattt/emcee/releases/download/v0.5.1/emcee_Darwin_x86_64.tar.gz"
      sha256 "aadb69c7044c56bde5aad872319c32bebc85b6fb45acf176c497c2294a8f39b1"

      def install
        bin.install "emcee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mattt/emcee/releases/download/v0.5.1/emcee_Darwin_arm64.tar.gz"
      sha256 "6718fe9cbc7ee9eca79bbd24ac73329f3594722a5a8e32fddb68818f42d5be2e"

      def install
        bin.install "emcee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mattt/emcee/releases/download/v0.5.1/emcee_Linux_x86_64.tar.gz"
      sha256 "637572334a2b7a04a59b77d40f891eb9155c57882a80bd0da10e71b8d3edb1aa"
      def install
        bin.install "emcee"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mattt/emcee/releases/download/v0.5.1/emcee_Linux_arm64.tar.gz"
      sha256 "cf42c014416d1b9c0e8e9080c41712bdc33c10e70b9b963665bad6dc0dd95288"
      def install
        bin.install "emcee"
      end
    end
  end
end
