# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emcee < Formula
  desc ""
  homepage ""
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mattt/emcee/releases/download/v0.8.0/emcee_Darwin_x86_64.tar.gz"
      sha256 "fae311d338a2fd21d711be58e91f86878b2fb54b52c19428845c47607002a1e6"

      define_method(:install) do
        bin.install "emcee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mattt/emcee/releases/download/v0.8.0/emcee_Darwin_arm64.tar.gz"
      sha256 "db76627c3c110b06ab5718e0621a7a87367d96908d5c217eac03a116881ca059"

      define_method(:install) do
        bin.install "emcee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattt/emcee/releases/download/v0.8.0/emcee_Linux_x86_64.tar.gz"
      sha256 "d362214e99f76cd98be14efcbe6f8a85848fa41c24cd329cdf98fe21edba2389"
      define_method(:install) do
        bin.install "emcee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattt/emcee/releases/download/v0.8.0/emcee_Linux_arm64.tar.gz"
      sha256 "589233410105ddc3123cb820442655687576301fbc7855f95fb268abd3ff4a87"
      define_method(:install) do
        bin.install "emcee"
      end
    end
  end
end
